export const DEFAULT_UI_TEXT = {
  financialAid: "Financial Aid",
  financialAidAssistant: "Financial Aid Assistant",
  newChat: "New chat",
  noConversationsYet: "No conversations yet.",
  closeSidebar: "Close sidebar",
  responseLanguage: "Response language",
  liveSupport: "Live Support",
  liveSupportClosed: "Live Support Closed",
  liveSupportAdvisor: "Chat with a Live Financial Aid Advisor",
  connected: "Connected",
  waitingForAdvisor: "Waiting for advisor",
  askPlaceholder: "Ask about BYU-Hawaii financial aid...",
  customQuestionPlaceholder: "Or type your own financial aid question...",
  enterToSend: "to send",
  shiftEnterForNewLine: "for a new line",
  stopGenerating: "Stop generating",
  stop: "Stop",
  sendMessage: "Send message",
  ask: "Ask",
  or: "or",
  introTitle: "How can I help you today?",
  introDescription: "Ask me about scholarships, tuition, FAFSA, grants, deadlines, and financial aid requirements at BYU-Hawaii.",
  supportHoursNote: "Live support follows Financial Aid office hours: Mon-Fri, 8 AM-5 PM HST. Closed devotionals and holidays.",
  handoffNotice: "Thanks - your request has been sent to the BYU-Hawaii Financial Aid team. An advisor will join when available. Please stay on this chat while you wait.",
  supportCompleteNotice: "This live support conversation has been marked complete. You can continue asking financial aid questions or start a new support request if needed.",
  supportClosedNotice: "This live support request was closed. You can start a new live support request if you still need help.",
  outsideHoursNotice: "Live support is currently outside Financial Aid office hours. The chatbot is still available for general BYU-Hawaii Financial Aid questions. For account-specific help, contact financialaid@byuh.edu or (808) 675-3316 during office hours.",
  sources: "Sources",
  answeredFromSources: "Answered from BYU-Hawaii Financial Aid sources",
  needsOfficialConfirmation: "Needs official confirmation",
  helpful: "Helpful",
  notHelpful: "Not helpful",
  copy: "Copy",
  copied: "Copied",
  liveSupportNotice: "Live support",
  advisorReplied: "BYU-Hawaii Financial Aid advisor [{agentName}] replied.",
  privacyReminder: "Please do not share Social Security numbers, passwords, bank details, or other sensitive personal information in this chat.",
  speakToHuman: "Live Support",
  emptyChat: "Ask a question to get started.",
  somethingWentWrong: "Something went wrong.",
  tryAgain: "Please try again or refresh the page.",
  advisorTyping: "Financial Aid Advisor is typing...",
  suggestedScholarships: "What scholarships are available?",
  suggestedApply: "How do I apply for financial aid?",
  suggestedFafsa: "What is FAFSA and do I need it?",
  suggestedDeadlines: "What are the financial aid deadlines?",
  followUpDocuments: "What documents do I need?",
  followUpDeadline: "What is the deadline?",
  followUpContact: "Who can I contact?",
  followUpApply: "How do I apply?",
  followUpScholarships: "What scholarships are available?",
}

export type UIText = typeof DEFAULT_UI_TEXT

export const STATIC_UI_TEXT_TRANSLATIONS: Record<string, Partial<UIText>> = {
  es: {
    financialAid: "Ayuda Financiera",
    financialAidAssistant: "Asistente de Ayuda Financiera",
    newChat: "Nuevo chat",
    noConversationsYet: "Aún no hay conversaciones.",
    closeSidebar: "Cerrar barra lateral",
    responseLanguage: "Idioma de respuesta",
    liveSupport: "Soporte en vivo",
    liveSupportClosed: "Soporte en vivo cerrado",
    liveSupportAdvisor: "Chatear con un asesor de Ayuda Financiera",
    connected: "Conectado",
    waitingForAdvisor: "Esperando a un asesor",
    askPlaceholder: "Pregunta sobre la ayuda financiera de BYU-Hawaii...",
    customQuestionPlaceholder: "O escribe tu propia pregunta sobre ayuda financiera...",
    enterToSend: "para enviar",
    shiftEnterForNewLine: "para una nueva línea",
    stopGenerating: "Detener generación",
    stop: "Detener",
    sendMessage: "Enviar mensaje",
    ask: "Preguntar",
    or: "o",
    introTitle: "¿Cómo puedo ayudarte hoy?",
    introDescription: "Pregúntame sobre becas, matrícula, FAFSA, subvenciones, fechas límite y requisitos de ayuda financiera en BYU-Hawaii.",
    supportHoursNote: "El soporte en vivo sigue el horario de la oficina de Ayuda Financiera: lunes a viernes, 8 AM-5 PM HST. Cerrado durante devocionales y días festivos.",
    handoffNotice: "Gracias. Tu solicitud ha sido enviada al equipo de Ayuda Financiera de BYU-Hawaii. Un asesor se unirá cuando esté disponible. Permanece en este chat mientras esperas.",
    supportCompleteNotice: "Esta conversación de soporte en vivo se marcó como completada. Puedes seguir haciendo preguntas sobre ayuda financiera o iniciar una nueva solicitud de soporte.",
    supportClosedNotice: "Esta solicitud de soporte en vivo fue cerrada. Puedes iniciar una nueva solicitud si aún necesitas ayuda.",
    outsideHoursNotice: "El soporte en vivo está fuera del horario de la oficina de Ayuda Financiera. El chatbot sigue disponible para preguntas generales sobre ayuda financiera de BYU-Hawaii. Para ayuda específica de tu cuenta, contacta a financialaid@byuh.edu o (808) 675-3316 durante el horario de oficina.",
    sources: "Fuentes",
    answeredFromSources: "Respondido con fuentes de Ayuda Financiera de BYU-Hawaii",
    needsOfficialConfirmation: "Necesita confirmación oficial",
    helpful: "Útil",
    notHelpful: "No útil",
    copy: "Copiar",
    copied: "Copiado",
    liveSupportNotice: "Soporte en vivo",
    advisorReplied: "El asesor de Ayuda Financiera de BYU-Hawaii {agentName} respondió.",
    privacyReminder: "No compartas números de Seguro Social, contraseñas, datos bancarios u otra información personal confidencial en este chat.",
    speakToHuman: "Soporte en vivo",
    emptyChat: "Haz una pregunta para comenzar.",
    somethingWentWrong: "Algo salió mal.",
    tryAgain: "Inténtalo de nuevo o actualiza la página.",
    advisorTyping: "Un asesor de Ayuda Financiera está escribiendo...",
    suggestedScholarships: "¿Qué becas están disponibles?",
    suggestedApply: "¿Cómo solicito ayuda financiera?",
    suggestedFafsa: "¿Qué es FAFSA y lo necesito?",
    suggestedDeadlines: "¿Cuáles son las fechas límite de ayuda financiera?",
    followUpDocuments: "¿Qué documentos necesito?",
    followUpDeadline: "¿Cuál es la fecha límite?",
    followUpContact: "¿Con quién puedo comunicarme?",
    followUpApply: "¿Cómo solicito?",
    followUpScholarships: "¿Qué becas están disponibles?",
  },
  fr: {
    financialAid: "Aide financière",
    financialAidAssistant: "Assistant d’aide financière",
    newChat: "Nouvelle discussion",
    noConversationsYet: "Aucune conversation pour le moment.",
    closeSidebar: "Fermer la barre latérale",
    responseLanguage: "Langue de réponse",
    liveSupport: "Assistance en direct",
    liveSupportClosed: "Assistance en direct fermée",
    liveSupportAdvisor: "Discuter avec un conseiller en aide financière",
    connected: "Connecté",
    waitingForAdvisor: "En attente d’un conseiller",
    askPlaceholder: "Posez une question sur l’aide financière de BYU-Hawaii...",
    customQuestionPlaceholder: "Ou saisissez votre propre question sur l’aide financière...",
    enterToSend: "pour envoyer",
    shiftEnterForNewLine: "pour une nouvelle ligne",
    stopGenerating: "Arrêter la génération",
    stop: "Arrêter",
    sendMessage: "Envoyer le message",
    ask: "Demander",
    or: "ou",
    introTitle: "Comment puis-je vous aider aujourd’hui ?",
    introDescription: "Posez-moi des questions sur les bourses, les frais de scolarité, FAFSA, les subventions, les dates limites et les exigences d’aide financière à BYU-Hawaii.",
    supportHoursNote: "L’assistance en direct suit les heures du bureau d’aide financière : lun-ven, 8 h-17 h HST. Fermé pendant les dévotionnels et les jours fériés.",
    handoffNotice: "Merci. Votre demande a été envoyée à l’équipe d’aide financière de BYU-Hawaii. Un conseiller vous rejoindra lorsqu’il sera disponible. Veuillez rester dans ce chat pendant l’attente.",
    supportCompleteNotice: "Cette conversation d’assistance en direct a été marquée comme terminée. Vous pouvez continuer à poser des questions ou démarrer une nouvelle demande.",
    supportClosedNotice: "Cette demande d’assistance en direct a été fermée. Vous pouvez démarrer une nouvelle demande si vous avez encore besoin d’aide.",
    outsideHoursNotice: "L’assistance en direct est actuellement hors des heures du bureau d’aide financière. Le chatbot reste disponible pour les questions générales. Pour une aide liée à votre compte, contactez financialaid@byuh.edu ou (808) 675-3316 pendant les heures de bureau.",
    sources: "Sources",
    answeredFromSources: "Réponse basée sur les sources d’aide financière de BYU-Hawaii",
    needsOfficialConfirmation: "Nécessite une confirmation officielle",
    helpful: "Utile",
    notHelpful: "Pas utile",
    copy: "Copier",
    copied: "Copié",
    liveSupportNotice: "Assistance en direct",
    advisorReplied: "Le conseiller en aide financière de BYU-Hawaii {agentName} a répondu.",
    privacyReminder: "Ne partagez pas de numéros de sécurité sociale, mots de passe, informations bancaires ou autres données personnelles sensibles dans ce chat.",
    speakToHuman: "Assistance en direct",
    emptyChat: "Posez une question pour commencer.",
    somethingWentWrong: "Une erreur s’est produite.",
    tryAgain: "Veuillez réessayer ou actualiser la page.",
    advisorTyping: "Un conseiller en aide financière est en train d’écrire...",
    suggestedScholarships: "Quelles bourses sont disponibles ?",
    suggestedApply: "Comment demander une aide financière ?",
    suggestedFafsa: "Qu’est-ce que FAFSA et en ai-je besoin ?",
    suggestedDeadlines: "Quelles sont les dates limites de l’aide financière ?",
    followUpDocuments: "Quels documents me faut-il ?",
    followUpDeadline: "Quelle est la date limite ?",
    followUpContact: "Qui puis-je contacter ?",
    followUpApply: "Comment faire une demande ?",
    followUpScholarships: "Quelles bourses sont disponibles ?",
  },
  tl: {
    financialAid: "Tulong Pinansyal",
    financialAidAssistant: "Assistant sa Tulong Pinansyal",
    newChat: "Bagong chat",
    noConversationsYet: "Wala pang pag-uusap.",
    closeSidebar: "Isara ang sidebar",
    responseLanguage: "Wika ng sagot",
    liveSupport: "Live Support",
    liveSupportClosed: "Sarado ang Live Support",
    liveSupportAdvisor: "Makipag-chat sa Financial Aid Advisor",
    connected: "Nakakonekta",
    waitingForAdvisor: "Naghihintay sa advisor",
    askPlaceholder: "Magtanong tungkol sa financial aid ng BYU-Hawaii...",
    customQuestionPlaceholder: "O i-type ang sarili mong tanong tungkol sa financial aid...",
    enterToSend: "para ipadala",
    shiftEnterForNewLine: "para sa bagong linya",
    stopGenerating: "Itigil ang pagsagot",
    stop: "Itigil",
    sendMessage: "Ipadala ang mensahe",
    ask: "Magtanong",
    or: "o",
    introTitle: "Paano kita matutulungan ngayon?",
    introDescription: "Magtanong tungkol sa scholarships, tuition, FAFSA, grants, deadlines, at financial aid requirements sa BYU-Hawaii.",
    supportHoursNote: "Ang live support ay sumusunod sa oras ng Financial Aid office: Lunes-Biyernes, 8 AM-5 PM HST. Sarado kapag devotionals at holidays.",
    handoffNotice: "Salamat. Naipadala na ang request mo sa BYU-Hawaii Financial Aid team. Sasali ang advisor kapag available. Manatili sa chat habang naghihintay.",
    supportCompleteNotice: "Minarkahan nang kumpleto ang live support conversation na ito. Maaari ka pa ring magtanong o magsimula ng bagong request.",
    supportClosedNotice: "Isinara ang live support request na ito. Maaari kang magsimula ng bagong request kung kailangan mo pa ng tulong.",
    outsideHoursNotice: "Sarado ngayon ang live support ng Financial Aid office. Available pa rin ang chatbot para sa pangkalahatang tanong. Para sa account-specific na tulong, kontakin ang financialaid@byuh.edu o (808) 675-3316 sa office hours.",
    sources: "Mga source",
    answeredFromSources: "Sinagot mula sa BYU-Hawaii Financial Aid sources",
    needsOfficialConfirmation: "Kailangan ng opisyal na kumpirmasyon",
    helpful: "Nakatulong",
    notHelpful: "Hindi nakatulong",
    copy: "Kopyahin",
    copied: "Nakopya",
    liveSupportNotice: "Live support",
    advisorReplied: "Sumagot ang BYU-Hawaii Financial Aid advisor na si {agentName}.",
    privacyReminder: "Huwag magbahagi ng Social Security numbers, passwords, bank details, o iba pang sensitibong personal na impormasyon sa chat na ito.",
    speakToHuman: "Live Support",
    emptyChat: "Magtanong para makapagsimula.",
    somethingWentWrong: "May nangyaring mali.",
    tryAgain: "Subukan muli o i-refresh ang page.",
    advisorTyping: "Nagta-type ang Financial Aid Advisor...",
    suggestedScholarships: "Anong scholarships ang available?",
    suggestedApply: "Paano ako mag-a-apply para sa financial aid?",
    suggestedFafsa: "Ano ang FAFSA at kailangan ko ba ito?",
    suggestedDeadlines: "Ano ang deadlines ng financial aid?",
    followUpDocuments: "Anong documents ang kailangan ko?",
    followUpDeadline: "Ano ang deadline?",
    followUpContact: "Sino ang puwede kong kontakin?",
    followUpApply: "Paano ako mag-a-apply?",
    followUpScholarships: "Anong scholarships ang available?",
  },
  bi: {
    financialAid: "Fainensol Aed",
    financialAidAssistant: "Fainensol Aed Asisten",
    newChat: "Niu toktok",
    noConversationsYet: "I no gat eni toktok yet.",
    closeSidebar: "Klosim saed menu",
    responseLanguage: "Lanwis blong ansa",
    liveSupport: "Laef Sapot",
    liveSupportClosed: "Laef Sapot i klos",
    liveSupportAdvisor: "Toktok wetem Fainensol Aed advaesa",
    connected: "Konek finis",
    waitingForAdvisor: "Wet long advaesa",
    askPlaceholder: "Askem long saed blong BYU-Hawaii fainensol aed...",
    customQuestionPlaceholder: "O raetem kwestin blong yu long fainensol aed...",
    enterToSend: "blong sendem",
    shiftEnterForNewLine: "blong niu laen",
    stopGenerating: "Stopem ansa",
    stop: "Stop",
    sendMessage: "Sendem mesej",
    ask: "Askem",
    or: "o",
    introTitle: "Hao mi save helpem yu tude?",
    introDescription: "Askem mi long saed blong scholarships, tuition, FAFSA, grants, deadlines, mo fainensol aed requirements long BYU-Hawaii.",
    supportHoursNote: "Laef sapot i folem taem blong Fainensol Aed ofis: Mon-Fri, 8 AM-5 PM HST. I klos long devotionals mo holidays.",
    handoffNotice: "Tank yu. Request blong yu i go finis long BYU-Hawaii Financial Aid team. Wan advaesa bae i joen taem hem i available. Plis stap long chat taem yu wet.",
    supportCompleteNotice: "Laef sapot toktok ia i finis. Yu save gohed blong askem fainensol aed kwestin o statem niu request.",
    supportClosedNotice: "Laef sapot request ia i klos. Yu save statem niu request sipos yu nidim help yet.",
    outsideHoursNotice: "Laef sapot i stap aotsaed long taem blong Fainensol Aed ofis. Chatbot i stap yet blong ol general BYU-Hawaii fainensol aed kwestin. Blong help long account blong yu, kontaktem financialaid@byuh.edu o (808) 675-3316 long office hours.",
    sources: "Ol sos",
    answeredFromSources: "Ansa i kam long BYU-Hawaii Fainensol Aed sos",
    needsOfficialConfirmation: "I nidim official confirmation",
    helpful: "I help",
    notHelpful: "I no help",
    copy: "Kopi",
    copied: "Kopi finis",
    liveSupportNotice: "Laef sapot",
    advisorReplied: "BYU-Hawaii Fainensol Aed advaesa {agentName} i ansa.",
    privacyReminder: "Plis no serem Social Security namba, password, bank details, o narafala sensitive personal information long chat ia.",
    speakToHuman: "Laef Sapot",
    emptyChat: "Askem wan kwestin blong stat.",
    somethingWentWrong: "Samting i rong.",
    tryAgain: "Plis traem bakegen o refresh page.",
    advisorTyping: "Fainensol Aed advaesa i stap raet...",
    suggestedScholarships: "Wanem scholarships i available?",
    suggestedApply: "Hao mi apply blong fainensol aed?",
    suggestedFafsa: "FAFSA hem i wanem mo mi nidim?",
    suggestedDeadlines: "Wanem deadlines blong fainensol aed?",
    followUpDocuments: "Wanem documents mi nidim?",
    followUpDeadline: "Wanem deadline?",
    followUpContact: "Hu nao mi save kontaktem?",
    followUpApply: "Hao mi apply?",
    followUpScholarships: "Wanem scholarships i available?",
  },
}

export function getStaticUIText(languageCode: string): UIText | null {
  const translation = STATIC_UI_TEXT_TRANSLATIONS[languageCode]
  return translation ? { ...DEFAULT_UI_TEXT, ...translation } : null
}
