export const DEFAULT_UI_TEXT = {
  financialAid: "Financial Aid",
  financialAidAssistant: "Financial Aid Assistant",
  newChat: "New chat",
  noConversationsYet: "No conversations yet.",
  closeSidebar: "Close sidebar",
  responseLanguage: "Response language",
  liveSupport: "Live Support",
  liveSupportClosed: "Live Support Closed",
  liveSupportAdvisor: "Chat with a Live Financial Aid Advisor",
  connected: "Connected",
  waitingForAdvisor: "Waiting for advisor",
  askPlaceholder: "Ask about BYU-Hawaii financial aid...",
  customQuestionPlaceholder: "Or type your own financial aid question...",
  enterToSend: "to send",
  shiftEnterForNewLine: "for a new line",
  stopGenerating: "Stop generating",
  stop: "Stop",
  sendMessage: "Send message",
  ask: "Ask",
  or: "or",
  introTitle: "How can I help you today?",
  introDescription: "Ask me about scholarships, tuition, FAFSA, grants, deadlines, and financial aid requirements at BYU-Hawaii.",
  sources: "Sources",
  answeredFromSources: "Answered from BYU-Hawaii Financial Aid sources",
  needsOfficialConfirmation: "Needs official confirmation",
  helpful: "Helpful",
  notHelpful: "Not helpful",
  copy: "Copy",
  copied: "Copied",
  liveSupportNotice: "Live support",
  advisorReplied: "BYU-Hawaii Financial Aid advisor [{agentName}] replied.",
  privacyReminder: "Please do not share Social Security numbers, passwords, bank details, or other sensitive personal information in this chat.",
  speakToHuman: "Live Support",
  emptyChat: "Ask a question to get started.",
  somethingWentWrong: "Something went wrong.",
  tryAgain: "Please try again or refresh the page.",
  advisorTyping: "Financial Aid Advisor is typing...",
  suggestedScholarships: "What scholarships are available?",
  suggestedApply: "How do I apply for financial aid?",
  suggestedFafsa: "What is FAFSA and do I need it?",
  suggestedDeadlines: "What are the financial aid deadlines?",
  followUpDocuments: "What documents do I need?",
  followUpDeadline: "What is the deadline?",
  followUpContact: "Who can I contact?",
  followUpApply: "How do I apply?",
  followUpScholarships: "What scholarships are available?",
}

export type UIText = typeof DEFAULT_UI_TEXT
